### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by ikzelf**

### CODE REVIEW

**Comment by ikzelf** [comment]
[zbxtg.py.zip](https://github.com/ableev/Zabbix-in-Telegram/files/1413416/zbxtg.py.zip)

**Comment by ikzelf** [comment]
don't remove image when in debug mode, added vim line and replace with emoji

**Comment by ableev** [comment]
@ikzelf what is it? Are you suggesting to download some zip archive? Or what?

**Comment by ikzelf** [comment]
Hi @ableev I guess I am doing something wrong here in git .... I tried to attach the modified zbxtg.py and that failed because: .py not supported. .zip is supported so I did put it in a zip file. I have no idea what I should have done instead

**Pull request closed without merging**
