### PR TITLE
Fix error when sending a private message

### PR DESCRIPTION
**Pull request by jtprogru**
Hi!
I can't understand this magic, but this work. When I'm sending a test private message, I have error 
`message_id must be integer, not string`

I'm fix it very simple =)

### CODE REVIEW

**Comment by ableev** [comment]
@jtprog if you could upload test result with input and output to gist - that would be useful.

**Comment by jtprog** [comment]
Unfortunately, the problem could not be repeated.
As I understand it, problems were associated with clearing the cache and restarting the bot.

**Comment by jtprog** [comment]
I'm not sure, but it seems somehow connected.
Below is a screenshot of the log.
When script run with `--debug` I view this error.

Снимок экрана 2019-04-29 в 14 32 53

**Comment by ableev** [comment]
@jtprog it has nothing to do with the script and your fix won't help. 

This means that you sent something else to the bot. 

Picture? Or something else? 
Instead of a message.
And the script couldn't find "message id", because there's no message in JSON from the server.

**Pull request closed without merging**
